### ISSUE TITLE
vimdiff leads to error messages

### ISSUE THREAD

**Issue by chza** [thepith/pdot#1]
![vimdiff_err](https://cloud.githubusercontent.com/assets/21059989/17699963/1223d346-63c4-11e6-82e2-5fdb08fde989.png)

**Comment by thepith** [comment]
This happens if mkview is called (when leaving the buffer) with a version of vim which has different features enabled than than the version used for vimdiff.

Check than `vim --version` and `vimdiff --version` have the same features included.
